services:
  oracle:
    image: container-registry.oracle.com/database/free:latest
    container_name: districtcore-oracle

    environment:
      ORACLE_PWD: ${ORACLE_PWD}
      ORACLE_CHARACTERSET: AL32UTF8

    ports:
      - "1521:1521"

    volumes:
      - oracle-data:/opt/oracle/oradata

    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: districtcore-keycloak

    command: start-dev

    ports:
      - "8080:8080"

    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

    volumes:
      - keycloak_data:/opt/keycloak/data

    restart: unless-stopped

volumes:
  oracle-data:
  keycloak_data: