CREATE TABLE job_positions (
    job_position_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    department_id       NUMBER NOT NULL,
    name                VARCHAR2(100) NOT NULL,
    description         VARCHAR2(500),

    CONSTRAINT pk_job_positions
        PRIMARY KEY (job_position_id),

    CONSTRAINT fk_job_positions_department_id
        FOREIGN KEY (department_id)
        REFERENCES departments(department_id),

    CONSTRAINT uq_job_positions_department
        UNIQUE (department_id, job_position_id),
        
    CONSTRAINT uq_job_positions_name
        UNIQUE (department_id, name)
);