CREATE TABLE roles (
    role_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR2(100) NOT NULL,
    description VARCHAR2(500),

    CONSTRAINT pk_roles_id
        PRIMARY KEY (role_id),

    CONSTRAINT uq_roles_name
        UNIQUE (name)    
);