CREATE TABLE permissions (
    permission_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR2(100) NOT NULL,
    description VARCHAR2(500),

    CONSTRAINT pk_permissions_id
        PRIMARY KEY (permission_id),

    CONSTRAINT uq_permission_name
        UNIQUE(name)
);