CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    identity_id     VARCHAR2(255) NOT NULL,
    username        VARCHAR2(100) NOT NULL,
    role_id         NUMBER NOT NULL,

    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_users_id
        PRIMARY KEY (user_id),

    CONSTRAINT fk_users_roles_id
        FOREIGN KEY (role_id)
        REFERENCES roles(role_id),

    CONSTRAINT uq_users_names
        UNIQUE (username),

    CONSTRAINT uq_users_identity_id
        UNIQUE (identity_id)
);