CREATE TABLE employees (
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id         NUMBER,
    first_name      VARCHAR2(100) NOT NULL,
    last_name       VARCHAR2(100) NOT NULL,
    department_id   NUMBER NOT NULL,
    job_position_id NUMBER NOT NULL,
    hire_date       DATE,
    status          VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,

    CONSTRAINT pk_employees_id
        PRIMARY KEY (employee_id),

    CONSTRAINT fk_employees_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),
    
    CONSTRAINT fk_employees_department
        FOREIGN KEY (department_id)
        REFERENCES departments(department_id),

    CONSTRAINT fk_employees_job_position_department
        FOREIGN KEY (job_position_id, department_id)
        REFERENCES job_positions(job_position_id, department_id),

    CONSTRAINT ck_employees_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'TERMINATED')),
    
    CONSTRAINT uq_employees_user
        UNIQUE (user_id)
);