CREATE TABLE audit_logs (
    audit_log_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id     NUMBER,
    action_done      VARCHAR2(100) NOT NULL,
    resource_used    VARCHAR2(100) NOT NULL,
    resource_id NUMBER,
    details     CLOB,
    ip_address  VARCHAR2(45),
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_audit_logs
        PRIMARY KEY (audit_log_id),

    CONSTRAINT fk_audit_logs_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
);